### ISSUE TITLE
"Introducing Expanded Security Maintenance" stays back after install fake-ua

### ISSUE THREAD

**Issue by Metrax** [Skyedra/UnspamifyUbuntu#2]
After install fake-ua, this message stays back in the motd, if ua already downloaded this message:
```
 * Introducing Expanded Security Maintenance for Applications.
   Receive updates to over 25,000 software packages with your
   Ubuntu Pro subscription. Free for personal use.

     https://ubuntu.com/pro
```

Please add:
`rm /var/lib/ubuntu-advantage/messages/motd-esm-announce`

To the removal instructions.

Thanks for these great instructions :-)

**Comment by Skyedra** [comment]
Hello there!

Thanks for kind words and the alternate strategy :)

FYI it is not needed to remove `/var/lib/ubuntu-advantage/messages/motd-esm-announce` as the directions in the MOTD section of the document ('Remove ESM MOTD Spam') will prevent the file from being read regardless of if using real ua or fake ua package.  Please give [those steps](https://github.com/Skyedra/UnspamifyUbuntu#removal-instructions) a go and let me know if that doesn't resolve it

**Comment by Metrax** [comment]
I did it with a fresh installation again, followed exactly the instratuctions and this is the result:
![image](https://user-images.githubusercontent.com/1061866/232739166-183d54eb-b2cb-4c9f-9d0d-95bd9fb86b9f.png)
The message still persist.

**Comment by Skyedra** [comment]
Ahhh, I see.  I think I actually directed you to the wrong part of the instructions based on where that spam is showing in the motd order.  Did you also try the [part 3: Remove Dynamic MOTD Spam](https://github.com/Skyedra/UnspamifyUbuntu#remove-dynamic-motd-spam)?  

If that doesn't work, I'm wondering if you could help me hunt down where it is coming from.  (I'm not seeing that spam on my VM, maybe because I'm testing with desktop vm instead of server vm -- I might have to set one of those up, too.)  Can you please run each of the scripts in `/etc/default/motd-news` and let me know which one outputs the spam?

**Comment by Skyedra** [comment]
Ah nevermind, I see that this is coming from `88-esm-announce` and the stock script doesn't provide _any_ way to disable it!  (Ugh, ubuntu!).  This is quite unfortunate for systems that require/wish to have ua installed, but as I don't see any workaround other than manually modifying `/etc/update-motd.d/88-esm-annouce` I will integrate the delete step you proposed

**Comment by Skyedra** [comment]
Updated, thanks again for the report
